export default Colors = {
	altTextColor: 'black',
	textColor: '#fff',
	darkTextColor: '#595948',
	backgroundColor: '#ffff91',
	secondaryColor: 'grey',
	appBorderColor: '#008080',
	iconColor: 'black',
	yesColor: 'green',
	noColor: 'red',
	underLineTextInput: 'black',
	dullGreen: '#9EC7BF',
	lightYellow: '#FBE6A3',
	mintGreen: '#91E3D0',
	paleGreen: '#BDD8D2',
	mustardYellow: '#FECE2F',
}
